### ISSUE TITLE
Uncaught Error: Could not find module `ember-concurrency` imported from `ember-scrollmagic/services/scroll-magic`

### ISSUE THREAD

**Issue by yawen0802** [willviles/ember-scrollmagic#13]
Hi Will,

First of all, thank you for creating this add-on! It is really cool and I would love to use it. After I installed it, I had an error that I don't know how to debug it. Below is the screenshot of the error. Could you please take a look and let me know if you have any questions. 

![screen shot 2018-06-26 at 8 59 38 am](https://user-images.githubusercontent.com/30669284/41917407-e6e75ae0-791f-11e8-8621-2066a1c7c324.png)

**Comment by jonnygreen** [comment]
The add-on needs `ember-concurrency` which isn't included as a dependency. To get around this, just install it separately:
```
ember install ember-concurrency
```

**Comment by yawen0802** [comment]
@jonnygreen  Thank you so much!!! It works now!

**Comment by willviles** [comment]
Hi @yawen0802 and @jonnygreen. I'll add `ember-concurrency` to the package.json in the next release!
